//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NousDemoApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImageUploadInfo
    {
        public int ImageNo { get; set; }
        public string ImageName { get; set; }
    }
}
